### ISSUE TITLE
I have an issue with fetching market data.

### ISSUE THREAD

**Issue by art1313** [project-serum/serum-js#33]
I run the following code:

```
import solanaWeb3 from '@solana/web3.js';
import serum from '@project-serum/serum';
const { Market } = serum;

let url;
url = 'https://api.mainnet-beta.solana.com';
//url = 'http://localhost:8899';
const connection = new solanaWeb3.Connection(url);


let marketAddress = new solanaWeb3.PublicKey('BJ3jrUzddfuSrZHXSCxMUUQsjKEyLmuuyZebkcaFp2fg'); //
let market = await Market.load(connection, marketAddress);

// Fetching orderbooks
let bids = await market.loadBids(connection);
let asks = await market.loadAsks(connection);

// L2 orderbook data
for (let [price, size] of bids.getL2(20)) {
  console.log(price, size);
}
// Full orderbook data
for (let order of asks) {
  console.log(
    order.orderId,
    order.price,
    order.size,
    order.side, // 'buy' or 'sell'
  );
}

```

Error log:

```
node_modules/@solana/web3.js/lib/index.cjs.js:103
      return this._bn.eq(publicKey._bn);
                                   ^

TypeError: Cannot read property '_bn' of undefined
    at PublicKey.equals (/Users/artem/Repos/node-dexes/node_modules/@solana/web3.js/lib/index.cjs.js:103:36)
    at Function.load (/Users/artem/Repos/node-dexes/node_modules/@project-serum/serum/lib/market.js:88:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///Users/artem/Repos/node-dexes/src/serum.js:20:14
```

**Comment by nathanielparke** [comment]
https://github.com/project-serum/serum-js/blob/master/src/market.ts

```
export class Market {
...
    static async load(
    connection: Connection,
    address: PublicKey,
    options: MarketOptions = {},
    programId: PublicKey,
  ) {...}
}
```

`Market.load` requires the `options` and `programId` parameters as well. This code is not passing those in.

**Comment by art1313** [comment]
@nathanielparke  Thanks for your response, what do I pass for options? 
Is it accurate list https://github.com/project-serum/serum-js/blob/master/src/markets.json to get Public Key, programId?

**Comment by nathanielparke** [comment]
For options you can pass an empty object, and it will work. These options are used to define the connection behavior with Solana validators. That is the correct list for `address` and `programId`. Note that you will probably want to avoid the markets with `deprecated` set to true.
